# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  lane :beta do
    ensure_git_branch(
      branch: "master"
    )
    git_pull

    # build the release variant
    gradle(task: "clean", project_dir: "android/")
    gradle(task: "assemble", build_type: "Release", project_dir: "android/")
    # upload to HockeyApp
    hockey(
      api_token: "a32f3ddbde5c4bb5abed4a02942e8bc8"
    )
  end
end
